config/routes.rb
Service::Application.routes.draw do

  resources :oauth_clients

  match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request
  match '/oauth/token',         :to => 'oauth#token',         :as => :token
  match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token
  match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token
  match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize
  match '/oauth/revoke',        :to => 'oauth#revoke',        :as => :revoke
  match '/oauth',               :to => 'oauth#index',         :as => :oauth

  devise_for :users
  
  devise_scope :user do
    get '/sign_in', :to => 'devise/sessions#new'
    match '/sign_out', :to => 'devise/sessions#destroy'
    get '/sign_up', :to => 'devise/registrations#new'
  end
  
  resources :users do
    resource :profile
  end

  match '/about' => 'welcome#about'
  match '/contact' => 'welcome#contact'

  root :to => "welcome#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample Service</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="user_nav">
    <%= link_to 'home', root_url %>
    <%= link_to 'about', about_url %>
    <%= link_to 'contact', contact_url %>
    |
    <% if user_signed_in? -%>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to 'sign out', sign_out_url, :method => :delete %>
      <%= link_to 'oauth', oauth_clients_url %>
      

    <% else -%>    
      <%= link_to 'sign up', new_user_registration_url %>
      <%= link_to 'sign in', sign_in_url %>
    <% end -%>
  </div>
  
  <div class="alert">
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span>
  </div>
    
  <%= yield %>
</body>
</html>